version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.optimized
      target: development
      args:
        PHP_VERSION: 8.3
    container_name: xgproyect-dev
    restart: unless-stopped
    environment:
      - APP_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=xgp
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - XDEBUG_MODE=develop,debug,coverage
      - XDEBUG_CONFIG=client_host=host.docker.internal
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
      - "9003:9003"  # Xdebug
    depends_on:
      - db
      - redis
    networks:
      - xgproyect-dev

  nginx:
    image: nginx:alpine
    container_name: xgproyect-nginx-dev
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - xgproyect-dev

  db:
    image: mysql:8.0
    container_name: xgproyect-db-dev
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: xgp
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33060:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - xgproyect-dev

  redis:
    image: redis:7-alpine
    container_name: xgproyect-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - xgproyect-dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: xgproyect-phpmyadmin-dev
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - xgproyect-dev

  mailhog:
    image: mailhog/mailhog
    container_name: xgproyect-mailhog-dev
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - xgproyect-dev

networks:
  xgproyect-dev:
    driver: bridge

volumes:
  mysql_data_dev:
